version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://admin:123@db:6543/Chat_API
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Chat_API
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
